
baseURL: "https://oktrik.com/"
languageCode: "en-us"
title: "OKTRIK"
theme: "oktrik-theme"

# Hugo configuration
disableKinds: ["taxonomy", "term"]
enableEmoji: true
enableRobotsTXT: true

# Menu
menu:
  main:
    - name: "Kategori"
      url: "/categories/"
      weight: 1
    - name: "Tutorials"
      url: "/tutorials/"
      weight: 2
    - name: "Tips & Tricks"
      url: "/tips-tricks/"
      weight: 3

# Permalinks
permalinks:
  posts: "/posts/:slug/"
  pages: "/:slug/"

# Site parameters
params:
  description: "Tech tutorials and tips for everyone"
  images: ["og-image.png"]
  mainSections: ["posts"]
  # Social media
  social:
    twitter: "oktrik"
    github: "oktrik"
